export default {
    //轮播图
    banners:[],
    //推荐歌单
    recommends:[],
    //推荐MV
    recommendMVs:[],
    //MV相关信息
    infoOfMvs:[],
    //点击播放mv的id
    mvId:0,
    //点击的歌单
    musiclist:{},
    //点击歌单的全部歌曲
    allmusic:[],
    //全部歌曲的暂存,和allmusic相等目的是暂存当前播放列表，使切换列表时，当前歌曲仍然可以播放
    tempAllMusic:[],
    //正在播放的歌曲
    playingmusic:{},
    //是否切换了歌曲
    isChanged:false,
    //播放歌曲的url
    playingurl:'',
    //播放歌曲的封面
    playingpic:'',
    //播放歌曲的歌词
    playinglyric:'',
    //歌词分割出来的时间数组
    arrTimeOfLyric:[],
    //当前歌词的下标
    currentIndex: 0,
    //当前歌词滚动条与歌曲时间对应时的所处位置
    currentPosition:0 ,
    //音量，因为store中数据存在了sessionStroage中，这样在刷新页面后，这个volume数据也不会丢失
    volume:0.6,
    //播放模式
    playmode:1,
    //是否正在播放
    isplaying: false,
    //正在播放歌曲在歌单中的index
    musicindex:0,  
    //正在播歌曲的歌单
    musiclistid:'',  
    //是否正在搜索
    issearch:false, 
    //是否是主页的搜索
    isMainSearch:false,
    //搜索结果
    searchresult:[],
    //历史记录
    historylist:[],
    //mv
    mv:{},
    //mv作者
    mvartist:{},
    //mv地址
    mvurl:'',
    //mv评论
    newcomments:[],
    //热门评论
    hotcomments:[],
    //相似mv
    simvs:[],
    //mv列表
    mvs:[],
    //没有更多了
    nomore:false,
    //是否滚到底部
    isbottom:false,
    //当前歌单页数
    plpage:1,
    //comment对象
    eventComment:{},
    //搜索关键词
    keyword:'',
    //搜索得到的歌单
    playlists:[],
    //所有分类
    alltypes:[],
    //当前分类
    type:'',
    //mv分类的遮罩
    mvcover:false,
    //mv的分类
    mvtypes:{
        area:'全部',
        type:'全部',
        order:'上升最快',
        limit:30,
        offset:0,
        mvpage:1
    },
    //显示/隐藏MV的信息
    mvhide:true
}